### ISSUE TITLE
Two motor tests

### ISSUE THREAD

**Issue by jackyj888** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#1]
Hello, I am also working on setting up a system with two motors using socketcan/python and I ran into your git repo. For my system, I am trying to connect two AK-60 motor onto the same CAN bus (each motor is set with a different CAN ID). The way I am doing is by connecting the two motor’s CAN bus pins onto the same CAN transceiver TI SN65HVD232D, which is then connected to a microcontroller. My current code can control a single motor without a problem. However, I start to have issues of receiving CAN messages after adding another motor on the same CAN bus. 
So I am curious about how you physically set up your system and were you able to get the two-motor system working? I tested both `performance_profiler_two_motors.py` and `two_motor_test.py` and they both ran into issues of unable to receive CAN messages or send command to the second motor. 
Thank you very much for your help!

**Comment by vyas-shubham** [comment]
For the setup, I used a PEAKCAN USB-CAN converter and connect both the motors on the same CAN bus along with a termination resistor. The code in this repository is only useful if you are using the socketcan protocol. Depending on the microcontroller you use, it might not use socketcan to communicate to the computer and then this repository isn't very applicable without major changes. Are you using socketcan? Or are you communicating on CAN via the microcontroller (instead of directly from the computer using CAN-USB + socketcan)?

**Comment by jackyj888** [comment]
I am using socketcan for my setup and I just figure out the bug in my system setup. Now the system works. Thank you very much for your help!
