### ISSUE TITLE
python-can vs socket

### ISSUE THREAD

**Issue by mrunaljsarvaiya** [dfki-ric-underactuated-lab/mini-cheetah-tmotor-python-can#2]
Curious as to why you decided to the `socket` interface as  opposed to `python-can`?

**Comment by vyas-shubham** [comment]
As these motors are used with a CAN-to-USB converter which interfaces using `SocketCAN`, the `python-can` library would also use `socket` in the background. As `socket` is a basic python library, using it instead of `python-can` reduces the number of external dependencies required for this driver. I'm also planning to get rid of the `bitstring` library so that the driver is standalone in the future. I also have a `C++` version of this driver which has zero other dependencies and I am planning to make a python version also with dependencies.

**Comment by mrunaljsarvaiya** [comment]
> As these motors are used with a CAN-to-USB converter which interfaces using `SocketCAN`, the `python-can` library would also use `socket` in the background. As `socket` is a basic python library, using it instead of `python-can` reduces the number of external dependencies required for this driver. I'm also planning to get rid of the `bitstring` library so that the driver is standalone in the future. I also have a `C++` version of this driver which has zero other dependencies and I am planning to make a python version also with dependencies.

Got it that makes sense!

On another note, have you ever had issued with the encoder giving you an unexpected value after a power cycle? I'm running into issues where say the encoder has value x when the power is on, if the power is turned off and motor does not move, the encoder value on powering it back on is significantly different than x

**Comment by vyas-shubham** [comment]
Personally, I haven’t seen such behavior. If I don’t move the motor, it stays at the same position value. I’d recommend checking the firmware on the motor. Also, for me, the best practice is always to set the zero position initially using the the function in the driver before starting any motion. Then I’m sure about the position at the start and work from there.
